export const addButton=document.getElementById("addStudent")
export const viewSpecific=document.getElementById("viewSpecificButton")
export const viewAll=document.getElementById("viewAllButton")
export const viewSpecificSpace=document.getElementById("viewSpecific")
export const viewAllSpace=document.getElementById("viewAll")
export const enterStudentArea=document.getElementById("enterStudent")